image: node:10.14.2-stretch
stages: [setup, build, deploy]
install:
  stage: setup
  cache:
    paths:
      - .cache/npm
  script:
    - &npm_install
        npm install --quiet --no-progress --cache=.cache/npm
build:
  stage: build
  only:
    - main
  script:
    - *npm_install
    - node_modules/.bin/gulp build
  artifacts:
    paths:
      - public
bundle-stable:
  stage: deploy
  only:
    - main
  cache:
    paths:
      - .cache/npm
  script:
    - *npm_install
    - node_modules/.bin/gulp bundle
  artifacts:
    paths:
      - build/ui-bundle.zip
bundle-dev:
  stage: deploy
  except:
    - main
  cache:
    paths:
      - .cache/npm
  script:
    - *npm_install
    - node_modules/.bin/gulp bundle
  artifacts:
    expire_in: 1 day # unless marked as keep from job page
    paths:
      - build/ui-bundle.zip
