image: node:10.14.2-stretch
stages: [setup, build, deploy]
install:
  stage: setup
  cache:
    paths:
      - .cache/npm
  script:
    - &npm_install
        npm install --quiet --no-progress --cache=.cache/npm
bundle-stable:
  stage: build
  only:
    - main
  script:
    - *npm_install
    - node_modules/.bin/gulp bundle
    - cp build/ui-bundle.zip public/ui-bundle.zip # Copy ui-bundle.zip to the public directory
  artifacts:
    paths:
      - build/ui-bundle.zip
      - public/ui-bundle.zip # Make ui-bundle.zip available in the artifacts
bundle-dev:
  stage: build
  except:
    - main
  cache:
    paths:
      - .cache/npm
  script:
    - *npm_install
    - node_modules/.bin/gulp bundle
  artifacts:
    expire_in: 1 day # unless marked as keep from job page
    paths:
      - build/ui-bundle.zip
pages:
  stage: deploy
  only:
    - main
  script:
    - *npm_install
    - node_modules/.bin/gulp preview:build
    - cp build/ui-bundle.zip public/
  artifacts:
    paths:
      - public
