image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - main

start:
  stage: test
  script:
    - npm run start
  needs:
    - build
  except:
    - main

pages:
  stage: deploy
  script:
    - cp -R public/_/* public/
  artifacts:
    paths:
      - public
  only:
    - main
