name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.14.2'

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: .cache/npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install --quiet --no-progress --cache=.cache/npm

      - name: Bundle
        run: npx gulp bundle

      - name: Prepare artifacts
        run: |
          mkdir -p public
          cp build/ui-bundle.zip public/ui-bundle.zip

      - name: Upload ui-bundle.zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: ui-bundle
          path: build/ui-bundle.zip

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: npx gulp preview:build
